### ISSUE TITLE
Django minimal support version 3.2

### ISSUE THREAD

**Issue by hmleal** [sandino/django-trumbowyg#14]
There's some errors while trying to use Django 4.x

For example:

1. `django.conf.urls` was deprecated in [Django 3.1](https://docs.djangoproject.com/en/4.1/releases/3.1/) and removed in Django 4.x
2. `HttpRequest.is_ajax()` was deprecated

I believe we can update the source code use Django 3.2 as the minimal supported version and add support for Django 4.x versions

OBS.: I'll create a PR for that. Thanks in advance

**Comment by sandino** [comment]
I would appreciate a PR, thank you!

**Comment by hmleal** [comment]
PR is done, can you merge it?

**Comment by sandino** [comment]
I've merged your PR, but it still doesn't work with Django 4.x
